### ISSUE TITLE
Incorrect alignment in first header

### ISSUE THREAD

**Issue by cichy1173** [teziovsky/product_card#4]
Hi,
First header has wrong alingment to the left side. Also Lenovos logo hides name of the product.

![obraz](https://user-images.githubusercontent.com/32648503/153091448-bcf876e5-7ac1-4450-8d9c-45b7c7c1ebdd.png)

I think first header should be centered like rest of the website :-)

**Comment by teziovsky** [comment]
Hi,
thanks for the opening issue. The whole project was old and I decided to rewrite styles from scratch.
Now should be better,
Best regards!

**Comment by cichy1173** [comment]
Now is looking great!
